### ISSUE TITLE
install missing packages

### ISSUE THREAD

**Issue by B1Sandmann** [sapcc/fedIPA#18]
- [ ] htop in `htop`
- [ ] top / ps in `procps-ng`
- [ ] dig / nslookup  in `bind-utils`
- [ ] ping in `iputils`
- [ ] tcpdump in `tcpdump`
- [ ] stress-ng in `stress-ng`
- [ ] fio in `fio`
- [ ]

**Comment by sandzwerg** [comment]
solved by #17
